const tarotDeck = [
  {
    name: 'The Fool',
    number: 0,
    image: 'src/assets/TarotDeck/the fool.png',
    meaning: 'New beginnings, adventure, opportunity',
    reversed: 'Carelessness, recklessness, foolishness',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'New beginnings, adventure, opportunity',
    majorArcana: true,
  },
  {
    name: 'The Magician',
    number: 1,
    image: 'src/assets/TarotDeck/themagician.png',
    meaning: 'Manifestation, creation, willpower',
    reversed: 'Manipulation, illusion, overconfidence',
    astrology: 'Mercury',
    element: 'Air',
    keywords: 'Manifestation, creation, willpower',
    majorArcana: true,
    
  },
  {
    name: 'The High Priestess',
    number: 2,
    image: 'src/assets/TarotDeck/highpresties.png',
    meaning: 'Intuition, mystery, wisdom',
    reversed: 'Mistrust, doubt, secrets revealed',
    astrology: 'Moon',
    element: 'Water',
    keywords: 'Intuition, mystery, wisdom',
    majorArcana: true,
  },
  {
    name: 'The Empress',
    number: 3,
    image: 'src/assets/TarotDeck/theempress.png',
    meaning: 'Femininity, creativity, abundance',
    reversed: 'Emotional dependency, overindulgence, victim mentality',
    astrology: 'Venus',
    element: 'Earth',
    keywords: 'Femininity, creativity, abundance',
    majorArcana: true,
  },
  {
    name: 'The Emperor',
    number: 4,
    image: 'src/assets/TarotDeck/theEmperor.png',
    meaning: 'Authority, structure, control',
    reversed: 'Domineering, stubbornness, rigidity',
    astrology: 'Mars',
    element: 'Fire',
    keywords: 'Authority, structure, control',
    majorArcana: true,
  },
  {
    name: 'The Hierophant',
    number: 5,
    image: 'src/assets/TarotDeck/theHierophant.png',
    meaning: 'Tradition, conformity, institutions',
    reversed: 'Rebellion, non-conformity, individuality',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Tradition, conformity, institutions',
    majorArcana: true,
  },
  {
    name: 'The Lovers',
    number: 6,
    image: 'src/assets/TarotDeck/theLovers.png',
    meaning: 'Love, harmony, relationships',
    reversed: 'Unrequited love, indecision, disharmony',
    astrology: 'Venus',
    element: 'Air',
    keywords: 'Love, harmony, relationships',
    majorArcana: true,
  },
  {
    name: 'The Chariot',
    number: 7,
    image: 'src/assets/TarotDeck/theChariot.png',
    meaning: 'Victory, control, willpower',
    reversed: 'Defeat, lack of control, surrender',
    astrology: 'Sun',
    element: 'Fire',
    keywords: 'Victory, control, willpower',
    majorArcana: true,
  },
  {
    name: 'Strength',
    number: 8,
    image: 'src/assets/TarotDeck/Strength.png',
    meaning: 'Courage, compassion, inner strength',
    reversed: 'Weakness, fear, cruelty',
    astrology: 'Leo',
    element: 'Fire',
    keywords: 'Courage, compassion, inner strength',
    majorArcana: true,
  },
  {
    name: 'The Hermit',
    number: 9,
    image: 'src/assets/TarotDeck/theHermit.png',
    meaning: 'Meditation, introspection, solitude',
    reversed: 'Withdrawal, isolation, loneliness',
    astrology: 'Virgo',
    element: 'Earth', 
    keywords: 'Meditation, introspection, solitude',
    majorArcana: true,
  },
  {
    name: 'Wheel of Fortune',
    number: 10,
    image: 'src/assets/TarotDeck/WheelOfFortune.png',
    meaning: 'Luck, karma, cycles',
    reversed: 'Bad luck, misfortune, stagnation',
    astrology: 'Jupiter',
    element: 'Air',
    keywords: 'Luck, karma, cycles',
    majorArcana: true,
  },
  {
    name: 'Justice',
    number: 11,
    image: 'src/assets/TarotDeck/Justice.png',
    meaning: 'Fairness, truth, cause and effect',
    reversed: 'Unfairness, dishonesty, imbalance',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Fairness, truth, cause and effect',
    majorArcana: true,
  },
  {
    name: 'The Hangman',
    number: 12,
    image: 'src/assets/TarotDeck/TheHangedMan.png',
    meaning: 'Sacrifice, enlightenment, new perspective',
    reversed: 'Self-sabotage, victim mentality, martyrdom',
    astrology: 'Neptune',
    element: 'Water',
    keywords: 'Sacrifice, enlightenment, new perspective',
    majorArcana: true,
  },
  {
    name: 'Death',
    number: 13,
    image: 'src/assets/TarotDeck/Death.png',
    meaning: 'Transformation, rebirth, letting go',
    reversed: 'Resistance to change, clinging to the past, stagnation',
    astrology: 'Scorpio',
    element: 'Water',
    keywords: 'Transformation, rebirth, letting go',
    majorArcana: true,
  },
  {
    name: 'Temperance',
    number: 14,
    image: 'src/assets/TarotDeck/Temperance.png',
    meaning: 'Balance, moderation, patience',
    reversed: 'Excess, lack of restraint, lack of self-control',
    astrology: 'Sagittarius',
    element: 'Fire',
    keywords: 'Balance, moderation, patience',
    majorArcana: true,
  },
  {
    name: 'The Devil',
    number: 15,
    image: 'src/assets/TarotDeck/TheDevil.png',
    meaning: 'Addiction, materialism, control',
    reversed: 'Freedom, release, liberation',
    astrology: 'Saturn',
    element: 'Earth',
    keywords: 'Addiction, materialism, control',
    majorArcana: true,
  },
  {
    name: 'The Tower',
    number: 16,
    image: 'src/assets/TarotDeck/theTower.png',
    meaning: 'Sudden change, upheaval, revelation',
    reversed: 'Sudden change averted, disruption avoided',
    astrology: 'Mars',
    element: 'Fire',
    keywords: 'Sudden change, upheaval, revelation',
    majorArcana: true,
  },
  {
    name: 'The Star',
    number: 17,
    image: 'src/assets/TarotDeck/TheStar.png',
    meaning: 'Hope, renewal, inspiration',
    reversed: 'Disappointment, despair, hopelessness',
    astrology: 'Jupiter',
    element: 'Air',
    keywords: 'Hope, renewal, inspiration',
    majorArcana: true,
  },
  {
    name: 'The Moon',
    number: 18,
    image: 'src/assets/TarotDeck/TheMoon.png',
    meaning: 'Illusions, fears, intuition',
    reversed: 'Clarity, reassurance, lucidity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Illusions, fears, intuition',
    majorArcana: true,
  },
  {
    name: 'The Sun',
    number: 19,
    image: 'src/assets/TarotDeck/TheSun.png',
    meaning: 'Happiness, success, fulfillment',
    reversed: 'Depression, disappointment, blocked creativity',
    astrology: 'Sun',
    element: 'Fire',
    keywords: 'Happiness, success, fulfillment',
    majorArcana: true,
  },
  {
    name: 'Judgement',
    number: 20,
    image: 'src/assets/TarotDeck/Judgement.png',
    meaning: 'Awakening, rebirth, atonement',
    reversed: 'Lack of self-awareness, missed opportunities',
    astrology: 'Uranus',
    element: 'Air',
    keywords: 'Awakening, rebirth, atonement',
    majorArcana: true,
  },
  {
    name: 'The World',
    number: 21,
    image: 'src/assets/TarotDeck/TheWorld.png',
    meaning: 'Completion, fulfillment, success',
    reversed: 'Incompletion, lack of fulfillment, stagnation',
    astrology: 'Saturn',
    element: 'Earth',
    keywords: 'Completion, fulfillment, success',
    majorArcana: true,
  },
  {
    name: 'Ace of Wands',
    number: 1,
    image: '',
    meaning: 'Creation, inspiration, new beginnings',
    reversed: 'Lack of direction, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Creation, inspiration, new beginnings',
    majorArcana: false,
  },
  {
    name: 'Two of Wands',
    number: 2,
    image: '',
    meaning: 'Expansion, adventure, exploration',
    reversed: 'Lack of direction, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Expansion, adventure, exploration',
    majorArcana: false,
  },
  {
    name: 'Three of Wands',
    number: 3,
    image: '',
    meaning: 'Expansion, adventure, exploration',
    reversed: 'Lack of direction, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Expansion, adventure, exploration',
    majorArcana: false,
  },
  {
    name: 'Four of Wands',
    number: 4,
    image: '',
    meaning: 'Celebration, success, achievement',
    reversed: 'Lack of celebration, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Celebration, success, achievement',
    majorArcana: false,
  },
  {
    name: 'Five of Wands',
    number: 5,
    image: '',
    meaning: 'Competition, conflict, struggle',
    reversed: 'Lack of competition, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Competition, conflict, struggle',
    majorArcana: false,
  },
  {
    name: 'Six of Wands',
    number: 6,
    image: '',
    meaning: 'Victory, success, recognition',
    reversed: 'Lack of recognition, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Victory, success, recognition',
    majorArcana: false,
  },
  {
    name: 'Seven of Wands',
    number: 7,
    image: '',
    meaning: 'Defending your position, standing your ground',
    reversed: 'Lack of defense, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Defending your position, standing your ground',
    majorArcana: false,
  },
  {
    name: 'Eight of Wands',
    number: 8,
    image: '',
    meaning: 'Rapid action, progress, movement',
    reversed: 'Lack of progress',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Rapid action, progress, movement',
    majorArcana: false,
  },
  {
    name: 'Nine of Wands',
    number: 9,
    image: '',
    meaning: 'Defending your position, standing your ground',
    reversed: 'Lack of defense, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Defending your position, standing your ground',
    majorArcana: false,
  },
  {
    name: 'Ten of Wands',
    number: 10,
    image: '',
    meaning: 'Overwhelm, burden, responsibility',
    reversed: 'Lack of responsibility, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Overwhelm, burden, responsibility',
    majorArcana: false,
  },
  {
    name: 'Page of Wands',
    number: 11,
    image: '',
    meaning: 'Enthusiasm, creativity, inspiration',
    reversed: 'Lack of enthusiasm, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Enthusiasm, creativity, inspiration',
    majorArcana: false,
  },
  {
    name: 'Knight of Wands',
    number: 12,
    image: '',
    meaning: 'Action, passion, movement',
    reversed: 'Lack of action, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Action, passion, movement',
    majorArcana: false,
  },
  {
    name: 'Queen of Wands',
    number: 13,
    image: '',
    meaning: 'Passion, creativity, inspiration',
    reversed: 'Lack of passion, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Passion, creativity, inspiration',
    majorArcana: false,
  },
  {
    name: 'King of Wands',
    number: 14,
    image: '',
    meaning: 'Passion, creativity, inspiration',
    reversed: 'Lack of passion, stagnation, blocked creativity',
    astrology: 'Aries',
    element: 'Fire',
    keywords: 'Passion, creativity, inspiration',
    majorArcana: false,
  },
  {
    name: 'Ace of Cups',
    number: 1,
    image: '',
    meaning: 'Love, compassion, creativity',
    reversed: 'Lack of love, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Love, compassion, creativity',
    majorArcana: false,
  },
  {
    name: 'Two of Cups',
    number: 2,
    image: '',
    meaning: 'Love, compassion, creativity',
    reversed: 'Lack of love, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Love, compassion, creativity',
    majorArcana: false,
  },
  {
    name: 'Three of Cups',
    number: 3,
    image: '',
    meaning: 'Celebration, friendship, community',
    reversed: 'Lack of celebration, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Celebration, friendship, community',
    majorArcana: false,
  },
  {
    name: 'Four of Cups',
    number: 4,
    image: '',
    meaning: 'Celebration, success, achievement',
    reversed: 'Lack of celebration, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Celebration, success, achievement',
    majorArcana: false,
  },
  {
    name: 'Five of Cups',
    number: 5,
    image: '',
    meaning: 'Loss, grief, sadness',
    reversed: 'Lack of loss, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Loss, grief, sadness',
    majorArcana: false,
  },
  {
    name: 'Six of Cups',
    number: 6,
    image: '',
    meaning: 'Celebration, success, achievement',
    reversed: 'Lack of celebration, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Celebration, success, achievement',
    majorArcana: false,
  },
  {
    name: 'Seven of Cups',
    number: 7,
    image: '',
    meaning: 'Fantasy, imagination, creativity',
    reversed: 'Lack of fantasy, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Fantasy, imagination, creativity',
    majorArcana: false,
  },
  {
    name: 'Eight of Cups',
    number: 8,
    image: '',
    meaning: 'Rapid action, progress, movement',
    reversed: 'Lack of progress, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Rapid action, progress, movement',
    majorArcana: false,
  },
  {
    name: 'Nine of Cups',
    number: 9,
    image: '',
    meaning: 'Celebration, success, achievement',
    reversed: 'Lack of celebration, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Celebration, success, achievement',
    majorArcana: false,
  },
  {
    name: 'Ten of Cups',
    number: 10,
    image: '',
    meaning: 'Celebration, success, achievement',
    reversed: 'Lack of celebration, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Celebration, success, achievement',
    majorArcana: false,
  },
  {
    name: 'Page of Cups',
    number: 11,
    image: '',
    meaning: 'Imagination, creativity, inspiration',
    reversed: 'Lack of imagination, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Imagination, creativity, inspiration',
    majorArcana: false,
  },
  {
    name: 'Knight of Cups',
    number: 12,
    image: '',
    meaning: 'Imagination, creativity, inspiration',
    reversed: 'Lack of imagination, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Imagination, creativity, inspiration',
    majorArcana: false,
  },
  {
    name: 'Queen of Cups',
    number: 13,
    image: '',
    meaning: 'Imagination, creativity, inspiration',
    reversed: 'Lack of imagination, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Imagination, creativity, inspiration',
    majorArcana: false,
  },
  {
    name: 'King of Cups',
    number: 14,
    image: '',
    meaning: 'Imagination, creativity, inspiration',
    reversed: 'Lack of imagination, stagnation, blocked creativity',
    astrology: 'Cancer',
    element: 'Water',
    keywords: 'Imagination, creativity, inspiration',
    majorArcana: false,
  },
  {
    name: 'Ace of Swords',
    number: 1,
    image: '',
    meaning: 'Truth, clarity, wisdom',
    reversed: 'Lack of truth, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Truth, clarity, wisdom',
    majorArcana: false,
  },
  {
    name: 'Two of Swords',
    number: 2,
    image: '',
    meaning: 'Balance, harmony, peace',
    reversed: 'Lack of balance, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Balance, harmony, peace',
    majorArcana: false,
  },
  {
    name: 'Three of Swords',
    number: 3,
    image: '',
    meaning: 'Heartbreak, sadness, grief',
    reversed: 'Lack of heartbreak, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Heartbreak, sadness, grief',
    majorArcana: false,
  },
  {
    name: 'Four of Swords',
    number: 4,
    image: '',
    meaning: 'Rest, relaxation, meditation',
    reversed: 'Lack of rest, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Rest, relaxation, meditation',
    majorArcana: false,
  },
  {
    name: 'Five of Swords',
    number: 5,
    image: '',
    meaning: 'Conflict, competition, struggle',
    reversed: 'Lack of conflict, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Conflict, competition, struggle',
    majorArcana: false,
  },
  {
    name: 'Six of Swords',
    number: 6,
    image: '',
    meaning: 'Journey, travel, transition',
    reversed: 'Lack of journey, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Journey, travel, transition',
    majorArcana: false,
  },
  {
    name: 'Seven of Swords',
    number: 7,
    image: '',
    meaning: 'Deception, trickery, manipulation',
    reversed: 'Lack of deception, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Deception, trickery, manipulation',
    majorArcana: false,
  },
  {
    name: 'Eight of Swords',
    number: 8,
    image: '',
    meaning: 'Imprisonment, restriction, limitation',
    reversed: 'Lack of imprisonment, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Imprisonment, restriction, limitation',
    majorArcana: false,
  },
  {
    name: 'Nine of Swords',
    number: 9,
    image: '',
    meaning: 'Anxiety, worry, fear',
    reversed: 'Lack of anxiety, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Anxiety, worry, fear',
    majorArcana: false,
  },
  {
    name: 'Ten of Swords',
    number: 10,
    image: '',
    meaning: 'Defeat, failure, loss',
    reversed: 'Lack of defeat, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Defeat, failure, loss',
    majorArcana: false,
  },
  {
    name: 'Page of Swords',
    number: 11,
    image: '',
    meaning: 'Truth, clarity, wisdom',
    reversed: 'Lack of truth, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Truth, clarity, wisdom',
    majorArcana: false,
  },
  {
    name: 'Knight of Swords',
    number: 12,
    image: '',
    meaning: 'Truth, clarity, wisdom',
    reversed: 'Lack of truth, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Truth, clarity, wisdom',
    majorArcana: false,
  },
  {
    name: 'Queen of Swords',
    number: 13,
    image: '',
    meaning: 'Truth, clarity, wisdom',
    reversed: 'Lack of truth, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Truth, clarity, wisdom',
    majorArcana: false,
  },
  {
    name: 'King of Swords',
    number: 14,
    image: '',
    meaning: 'Truth, clarity, wisdom',
    reversed: 'Lack of truth, stagnation, blocked creativity',
    astrology: 'Libra',
    element: 'Air',
    keywords: 'Truth, clarity, wisdom',
    majorArcana: false,
  },
  {
    name: 'Ace of Pentacles',
    number: 1,
    image: '',
    meaning: 'Abundance, prosperity, wealth',
    reversed: 'Lack of abundance, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Abundance, prosperity, wealth',
    majorArcana: false,
  },
  {
    name: 'Two of Pentacles',
    number: 2,
    image: '',
    meaning: 'Balance, harmony, peace',
    reversed: 'Lack of balance, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Balance, harmony, peace',
    majorArcana: false,
  },
  {
    name: 'Three of Pentacles',
    number: 3,
    image: '',
    meaning: 'Collaboration, teamwork, partnership',
    reversed: 'Lack of collaboration, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Collaboration, teamwork, partnership',
    majorArcana: false,
  },
  {
    name: 'Four of Pentacles',
    number: 4,
    image: '',
    meaning: 'Materialism, greed, hoarding',
    reversed: 'Lack of materialism, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Materialism, greed, hoarding',
    majorArcana: false,
  },
  {
    name: 'Five of Pentacles',
    number: 5,
    image: '',
    meaning: 'Poverty, scarcity, loss',
    reversed: 'Lack of poverty, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Poverty, scarcity, loss',
    majorArcana: false,
  },
  {
    name: 'Six of Pentacles',
    number: 6,
    image: '',
    meaning: 'Generosity, charity, giving',
    reversed: 'Lack of generosity, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Generosity, charity, giving',
    majorArcana: false,
  },
  {
    name: 'Seven of Pentacles',
    number: 7,
    image: '',
    meaning: 'Hard work, patience, perseverance',
    reversed: 'Lack of hard work, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Hard work, patience, perseverance',
    majorArcana: false,
  },
  {
    name: 'Eight of Pentacles',
    number: 8,
    image: '',
    meaning: 'Hard work, patience, perseverance',
    reversed: 'Lack of hard work, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Hard work, patience, perseverance',
    majorArcana: false,
  },
  {
    name: 'Nine of Pentacles',
    number: 9,
    image: '',
    meaning: 'Luxury, comfort, pleasure',
    reversed: 'Lack of luxury, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Luxury, comfort, pleasure',
    majorArcana: false,
  },
  {
    name: 'Ten of Pentacles',
    number: 10,
    image: '',
    meaning: 'Wealth, prosperity, abundance',
    reversed: 'Lack of wealth, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Wealth, prosperity, abundance',
    majorArcana: false,
  },
  {
    name: 'Page of Pentacles',
    number: 11,
    image: '',
    meaning: 'Wealth, prosperity, abundance',
    reversed: 'Lack of wealth, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Wealth, prosperity, abundance',
    majorArcana: false,
  },
  {
    name: 'Knight of Pentacles',
    number: 12,
    image: '',
    meaning: 'Wealth, prosperity, abundance',
    reversed: 'Lack of wealth, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Wealth, prosperity, abundance',
    majorArcana: false,
  },
  {
    name: 'Queen of Pentacles',
    number: 13,
    image: '',
    meaning: 'Wealth, prosperity, abundance',
    reversed: 'Lack of wealth, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Wealth, prosperity, abundance',
    majorArcana: false,
  },
  {
    name: 'King of Pentacles',
    number: 14,
    image: '',
    meaning: 'Wealth, prosperity, abundance',
    reversed: 'Lack of wealth, stagnation, blocked creativity',
    astrology: 'Taurus',
    element: 'Earth',
    keywords: 'Wealth, prosperity, abundance',
    majorArcana: false,
  },
];

export default tarotDeck;
